/*
 * Licensed to the Sakai Foundation (SF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The SF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package org.sakaiproject.nakamura.grouper.api;

import java.net.URL;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

import org.apache.commons.httpclient.HttpClient;

/**
 * A central place to hold configuration about a remote Grouper installation.
 * This is used during the sync and batch event processing.
 */
public interface GrouperConfiguration {

	// ------------------------- Connecting to Grouper ------------------------

	/**
	 * @return disable communication with grouper.
	 */
	public abstract boolean getDisableForTesting();

	/**
	 * @return the username in Grouper
	 */
	public abstract String getUsername();

	/**
	 * @return the username's password in Grouper
	 */
	public abstract String getPassword();

	/**
	 * @return the {@link URL} of the Grouper WS
	 */
	public abstract URL getUrl();

	/**
	 * How long to wait for an {@link HttpClient} request to fail.
	 * @return
	 */
	public abstract int getHttpTimeout();

	// ------------------------- Ignoring Events ------------------------

	/**
	 * Don't process events generated by this user.
	 * Prevents the dreaded "event-loop" where we keep informing Grouper of something it just did.
	 * @return the userId to ignore.
	 */
	public abstract String[] getIgnoredUsersEvents();

	/**
	 * Log in as this user to perform administrative tasks. Should not be admin.
	 * @return
	 */
	public abstract String getGrouperAdministratorUserId();

	/**
	 * Ignore groups that one match these patterns.
	 * @return the {@link Pattern}s to ignore.
	 */
	public abstract String[] getIgnoredGroups();

	// ------------------------ Group Folders in Grouper -----------------------

	/**
	 * @return where in grouper the user contacts groups are stored.
	 */
	public abstract String getContactsStem();

	/**
	 * @return where in grouper the adhoc simple groups are stored.
	 */
	public abstract String getSimpleGroupsStem();

	/**
	 * @return where in grouper the adhoc course groups are stored in grouper.
	 */
	public abstract String getAdhocCoursesStem();

	/**
	 * @return where in grouper the provisioned course groups are stored in grouper.
	 */
	public abstract String getProvisionedCoursesStem();

	/**
	 * Where the institutional courses are stored.
	 * @return
	 */
	public abstract String getInstitutionalCoursesStem();

	// --------------------- Identifying and Mapping Groups --------------------

	/**
	 * Groups in nakamura that have some special meaning.
	 * These are usually the -managers, -ta, and -lecturers.
	 * @return
	 */
	public abstract Set<String> getPseudoGroupSuffixes();


	/**
	 * @return a map of psuedoGroup extensions to grouper extensions.
	 */
	public abstract Map<String,String> getExtensionOverrides();

	/**
	 * This allows us to map group extensions in the institutional stems to the application stems.
	 * @return the mapping of extensions from application groups to institutional groups.
	 */
	public abstract Map<String, String> getInstitutionalExtensionOverrides();

	// --------------------- Policy  --------------------

	/**
	 * @return if groups will be deleted in Grouper when deleted in Sakai OAE
	 */
	public abstract boolean getDeletesEnabled();

	/**
	 * @return the maximum number of times we will retry processing a Message for the
	 * running sync component
	 */
	public abstract int getSyncMaxMessageRetries();

	/**
	 * @return the maximum number of times we will retry processing a Message for the
	 * batch component
	 */
	public abstract int getBatchMaxMessageRetries();

	/**
	 * @return the multiplier to use when computing the retry interval.
	 */
	public abstract int getJmsBackoffMultiplier();

	/**
	 * @return the email address to send notifications
	 */
	public abstract String getNotificationRecipient();

	/**
	 * @return the number of milliseconds to wait before a message is considered slow.
	 */
	public abstract long getSlowMessageThreshold();

}